.sparse/makepkg-git: include the bare minimum to build Rust stuff
This modifies the sparse checkout definition for building the
`mingw-w64-git` package by including the bits and pieces required to
build also the Rust parts of Git.

It comes at a hefty cost, though: the `git-sdk-x86_64-build-installers`
artifact will grow by ~108MB, which increase its size substantially (it
currently weighs 180MB).

Nevertheless, this is what is required to accommodate for upstream Git's
plan to make the Rust parts mandatory with v3.0.

Note: This _requires_ the `RUSTFLAGS` to be defined as `-C linker=gcc`,
or when `CARGO_BUILD_TARGET` is set to `x86_64-pc-windows-gnu`,
`CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=gcc`, otherwise the build
will fail with:

  error: linker `x86_64-w64-mingw32-gcc` not found

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>