Manually install msys2-runtime
The previous msys2-runtime version was botched [*1*] and produced an
invalid /usr/ssl/certs/ca-bundle.crt file, causing pacman itself to fail
in retrieving Git for Windows' Pacman's package database, hence the CI
job failed to pick up the newer msys2-runtime version. The symptom looks
like this:

	C:\git-sdk-64-ci>usr\bin\pacman -Syyu
	:: Synchronizing package databases...
	error: failed retrieving file 'git-for-windows.db' from dl.bintray.com :
	error setting certificate verify locations:
	  CAfile: /usr/ssl/certs/ca-bundle.crt
	    CApath: none
	error: failed to update git-for-windows (download library error)
	error: failed retrieving file 'git-for-windows-mingw32.db' from dl.bintray.com :
	error setting certificate verify locations:
	  CAfile: /usr/ssl/certs/ca-bundle.crt
	    CApath: none
	error: failed to update git-for-windows-mingw32 (download library error)

Let's just update msys2-runtime (and msys2-runtime-devel, which is
version-coupled) manually.

Footnote *1*:
https://github.com/git-for-windows/msys2-runtime/commit/874e2c8efeed

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>